blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/askable-ui/askable/discussions
    about: Ask questions and discuss ideas in GitHub Discussions
